const User = require('../Models/UserSchema');
const PatientProfile = require('../Models/PatientSchema');
const DoctorProfile = require('../Models/DoctorSchema');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');

const JWT_SECRET = process.env.JWT_SECRET || 'YOUR_SECRET_KEY';

const verifyToken = (req, res, next) => {
    const token = req.headers['authorization']?.split(' ')[1];
    if (!token) return res.status(403).json({ message: 'No token provided' });
    jwt.verify(token, JWT_SECRET, (err, decoded) => {
        if (err) return res.status(401).json({ message: 'Unauthorized' });
        req.userId = decoded.id;
        req.userRole = decoded.role;
        next();
    });
};

const register = async (req, res) => {
    try {
        const { name, email, password, role, gender, age, phone, specialization, experience, qualification, consultationFee, bio } = req.body;
        
        // Check if user already exists
        const existingUser = await User.findOne({ email });
        if (existingUser) {
            return res.status(400).json({ message: 'User already exists' });
        }

        // Validate doctor requirements
        if (role === 'doctor') {
            if (!specialization || specialization.trim() === '') {
                return res.status(400).json({ message: 'Specialization is required for doctors' });
            }
            if (experience === undefined || experience === '' || isNaN(parseInt(experience, 10))) {
                return res.status(400).json({ message: 'Valid experience (number) is required for doctors' });
            }
        }

        // Hash password
        const hashedPassword = await bcrypt.hash(password, 10);

        // Create new user (doctorUniqueId will be auto-generated by schema hook if role is doctor)
        const newUser = new User({
            name,
            email,
            password: hashedPassword,
            role: role || 'patient'
        });

        // Save to DB (schema hook will generate doctorUniqueId for doctors)
        const savedUser = await newUser.save();

        // Create Profile based on role
        if (savedUser.role === 'patient') {
            const patientData = { userId: savedUser._id };
            if (gender) patientData.gender = gender;
            if (age && !isNaN(parseInt(age, 10))) patientData.age = parseInt(age, 10);
            if (phone) patientData.phone = phone;
            await PatientProfile.create(patientData);
        } else if (savedUser.role === 'doctor') {
            const doctorData = {
                userId: savedUser._id,
                specialization: specialization.trim(),
                experience: parseInt(experience, 10),
                qualification: qualification || '',
                consultationFee: !isNaN(parseFloat(consultationFee)) ? parseFloat(consultationFee) : 0,
                bio: bio || ''
            };
            await DoctorProfile.create(doctorData);
        }

        res.status(201).json({ 
            success: true, 
            message: 'User registered successfully', 
            userId: savedUser._id, 
            role: savedUser.role,
            doctorUniqueId: savedUser.doctorUniqueId || null
        });
    } catch (error) {
        console.error("Registration Error:", error);
        res.status(500).json({ success: false, message: 'Server error during registration', error: error.message });
    }
};

const login = async (req, res) => {
    try {
        const { username, password, role } = req.body;
        
        // Check if user exists
        const user = await User.findOne({ email: username });
        if (!user) {
            return res.status(404).json({ success: false, message: 'User not found' });
        }

        // Check role
        if (role && user.role !== role) {
            return res.status(403).json({ success: false, message: 'Role mismatch' });
        }

        // Validate password
        const isMatch = await bcrypt.compare(password, user.password);
        if (!isMatch) {
            return res.status(400).json({ success: false, message: 'Invalid credentials' });
        }

        // Create token
        const token = jwt.sign(
            { id: user._id, role: user.role },
            JWT_SECRET,
            { expiresIn: '1d' }
        );

        res.json({
            success: true,
            token,
            user: {
                id: user._id,
                name: user.name,
                email: user.email,
                role: user.role,
                doctorUniqueId: user.doctorUniqueId
            }
        });
    } catch (error) {
        console.error("Login Error:", error);
        res.status(500).json({ success: false, message: 'Server error during login' });
    }
};

const getCurrentUser = async (req, res) => {
    try {
        const user = await User.findById(req.userId).select('-password');
        if (!user) return res.status(404).json({ message: 'User not found' });
        res.json(user);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

const logout = (req, res) => {
    res.json({ success: true, message: 'Logged out successfully' });
};

module.exports = {
    verifyToken,
    register,
    login,
    getCurrentUser,
    logout
};